#!/usr/bin/env ruby

require 'hatenablog_publisher'
require 'optparse'
require 'active_support/core_ext/hash'

args = ARGV.getopts('',
                    'draft',
                    'user:',
                    'site:',
                    'ad_type:',
                    'ad_file:',
                    'filename:',
                    'config:',
                    'data_file:',
                    'custom_path:',
                    'trace').symbolize_keys

HatenablogPublisher.publish(args)
