name: tagpr

on:
  push:
    branches: ["master"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: Songmu/tagpr@9bbb945b2fb025126186661e27d55485e3fc6df6 # v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
